
=head1 NAME

    hww-apply-headline - rename if modified headlines.


=head1 SYNOPSIS

    perl hww.pl apply-headline [--] <file>
    perl hww.pl apply-headline -a|--all


=head1 DESCRIPTION

rename filenames of entry files if new/deleted headlines found.
if you want to name entry files on yourself, you don't need to use this.


=head1 OPTIONS

=over

=item -a, --all

check and rename all files.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>


