
=head1 NAME

    hww-release - upload entries to hatena diary


=head1 SYNOPSIS

    perl hww.pl release [-t | --trivial]


=head1 DESCRIPTION

upload entries to hatena diary.
this command calls hw.pl internally.


=head1 TODO

we will rewrite old subroutines which does not use Hatena AtomPub API in the future.
(these old subroutines were written when Hatena AtomPub API does not exist)


=head1 OPTIONS

=over

=item -t, --trivial

upload entries as trivial. see also perldoc -F hw.pl about '-t' option.
this is identical with 'update' command.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>

