
=head1 NAME

    hww-chain - chain commands with '--'


=head1 SYNOPSIS

    perl hww.pl chain [COMMANDS [-- COMMANDS ...]]


=head1 EXAMPLES

    # show help and version.
    $ perl hww.pl chain help -- version

    # this is equivalent to 'perl hww.pl gen-html -I index.tmpl from to'.
    $ perl hww.pl chain gen-html from to -- update-index index.tmpl to


=head1 OPTIONS

No options.


=head1 AUTHOR

tyru <tyru.exe@gmail.com>


