
=head1 NAME

    hww-update - post entries to hatena diary as trivial


=head1 SYNOPSIS

    perl hww.pl update [same as 'release' arguments]


=head1 DESCRIPTION

this command is identical to B<release> command with B<--trivial> option.
see B<release> for the detail.


=head1 OPTIONS

see 'perl hww.pl help release'.


=head1 AUTHOR

tyru <tyru.exe@gmail.com>

