
=head1 NAME

    hww-load - load entries from hatena diary


=head1 SYNOPSIS

    perl hww.pl load [-a | --all] [-d | --draft] [--] <directory>
    or
    perl hww.pl load <YYYY-MM-DD>


=head1 DESCRIPTION

load entries from hatena diary.
if you don't give any options, load diary of YYYY-MM-DD.
see hw.pl's '-l' option.


=head1 OPTIONS

=over

=item -a, --all

fetch all entries.

=item -d, --draft

fetch all draft entries.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
