
=head1 NAME

    hww-release - post entries to hatena diary


=head1 SYNOPSIS

    perl hww.pl release [-t | --trivial]


=head1 DESCRIPTION

post entries to hatena diary.
this command calls hw.pl internally.


=head1 TODO

we will rewrite old subroutines which does not use Hatena AtomPub API in the future.
(these old subroutines were written when Hatena AtomPub API does not exist)


=head1 OPTIONS

=over

=item -t, --trivial

post entries as trivial. see also perldoc -F hw.pl about B<-t> option.
B<release -t> is identical with B<update> command.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>

