
=head1 NAME

    hww-status - show information about entry files


=head1 SYNOPSIS

    perl hww.pl status [-a | --all] [-C | --no-caption]


=head1 DESCRIPTION

currently this command just shows updated entries to be posted.


=head1 OPTIONS

=over

=item -a, --all

show all entry files.

=item -C, --no-caption

do not show caption and indent.
this option might be useful to pass other executable commands.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>


