
=head1 NAME

    hww-touch - update 'touch.txt'


=head1 SYNOPSIS

    perl hww.pl touch [<date format>]


=head1 DESCRIPTION

update B<touch.txt> in current date.
this command updates B<touch.txt>'s DATA (not mtime).
<date format> was parsed by Date::Manip module.
so if you want to make B<touch.txt>'s date older or newer,
you need to install Date::Manip.


=head1 OPTIONS

No options.


=head1 AUTHOR

tyru <tyru.exe@gmail.com>


