
=head1 NAME

    hww-help - display help information about hww


=head1 SYNOPSIS

    perl hww.pl help [COMMAND]


=head1 DESCRIPTION

show help.
or if command name was given, show help about its command.
(help text is written as pod under lib-hww/pod/)


=head1 OPTIONS

No options.


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
