
=head1 NAME

    hww-verify - verify misc information


=head1 SYNOPSIS

    perl hww.pl verify [--html] [--] [<directory>]


=head1 DESCRIPTION

currently this command just verify that
entry files or html files doesn't duplicate other files.


=head1 OPTIONS

=over

=item --html

verify html directory.
this changes suffix to verify to '*.html'.
(default is '*.txt')

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>


