
=head1 NAME

    hww-gen-html - generate htmls from entry files


=head1 SYNOPSIS

    perl hww.pl gen-html [OPTIONS] [--] <directory-from> <directory-to>
    perl hww.pl gen-html [OPTIONS] [--] <file-from> <file-to>



=head1 DESCRIPTION

if two paths are both directories (or second path doesn't exist),
generate htmls in second directory from entry files in first directory

if two path are both files (or second path doesn't exist),
generate a html to second path from first path.

and if you give B<-i> option, exec B<update-index> command
after this command performed.


=head1 OPTIONS

=over

=item -i, --update-index

directory:
this performs 'perl hww.pl update-index <directory-to>'.

file:
this performs 'perl hww.pl update-index <directory of file-to>'.

=item -I <template file>

directory:
this performs 'perl hww.pl update-index <directory-to> <template file>'.

file:
this performs 'perl hww.pl update-index <directory of file-to> <template file>'.

=item -m, --missing-only

generate only missing html files.

=back



=head1 AUTHOR

tyru <tyru.exe@gmail.com>


